repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  
  # - repo: https://github.com/psf/black
  #   rev: 24.4.2
  #   hooks:
  #     - id: black
  #       language_version: python3.12
  #       args:
  #         - --line-length=128

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v3.2.3
  #   hooks:
  #     - id: pylint